/*
 * NabooApi V1
 * Here you have the first version of the naboo api to create checkout automatically
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.Arrays;
import org.openapitools.client.model.Wallet;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for GetAccountResponse
 */
public class GetAccountResponseTest {
    private final GetAccountResponse model = new GetAccountResponse();

    /**
     * Model tests for GetAccountResponse
     */
    @Test
    public void testGetAccountResponse() {
        // TODO: test GetAccountResponse
    }

    /**
     * Test the property 'accountNumber'
     */
    @Test
    public void accountNumberTest() {
        // TODO: test accountNumber
    }

    /**
     * Test the property 'balance'
     */
    @Test
    public void balanceTest() {
        // TODO: test balance
    }

    /**
     * Test the property 'accountIsActivate'
     */
    @Test
    public void accountIsActivateTest() {
        // TODO: test accountIsActivate
    }

    /**
     * Test the property 'methodOfPayment'
     */
    @Test
    public void methodOfPaymentTest() {
        // TODO: test methodOfPayment
    }

    /**
     * Test the property 'loyaltyCredit'
     */
    @Test
    public void loyaltyCreditTest() {
        // TODO: test loyaltyCredit
    }

}
