/*
 * NabooApi V1
 * Here you have the first version of the naboo api to create checkout automatically
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for TransactionResponse
 */
public class TransactionResponseTest {
    private final TransactionResponse model = new TransactionResponse();

    /**
     * Model tests for TransactionResponse
     */
    @Test
    public void testTransactionResponse() {
        // TODO: test TransactionResponse
    }

    /**
     * Test the property 'orderId'
     */
    @Test
    public void orderIdTest() {
        // TODO: test orderId
    }

    /**
     * Test the property 'methodOfPayment'
     */
    @Test
    public void methodOfPaymentTest() {
        // TODO: test methodOfPayment
    }

    /**
     * Test the property 'amount'
     */
    @Test
    public void amountTest() {
        // TODO: test amount
    }

    /**
     * Test the property 'amountToPay'
     */
    @Test
    public void amountToPayTest() {
        // TODO: test amountToPay
    }

    /**
     * Test the property 'currency'
     */
    @Test
    public void currencyTest() {
        // TODO: test currency
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    public void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'transactionStatus'
     */
    @Test
    public void transactionStatusTest() {
        // TODO: test transactionStatus
    }

    /**
     * Test the property 'isEscrow'
     */
    @Test
    public void isEscrowTest() {
        // TODO: test isEscrow
    }

    /**
     * Test the property 'isMerchant'
     */
    @Test
    public void isMerchantTest() {
        // TODO: test isMerchant
    }

    /**
     * Test the property 'checkoutUrl'
     */
    @Test
    public void checkoutUrlTest() {
        // TODO: test checkoutUrl
    }

}
