/*
 * NabooApi V1
 * Here you have the first version of the naboo api to create checkout automatically
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.ProductModel;
import org.openapitools.client.model.Wallet;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for TransactionRequest
 */
public class TransactionRequestTest {
    private final TransactionRequest model = new TransactionRequest();

    /**
     * Model tests for TransactionRequest
     */
    @Test
    public void testTransactionRequest() {
        // TODO: test TransactionRequest
    }

    /**
     * Test the property 'methodOfPayment'
     */
    @Test
    public void methodOfPaymentTest() {
        // TODO: test methodOfPayment
    }

    /**
     * Test the property 'products'
     */
    @Test
    public void productsTest() {
        // TODO: test products
    }

    /**
     * Test the property 'successUrl'
     */
    @Test
    public void successUrlTest() {
        // TODO: test successUrl
    }

    /**
     * Test the property 'errorUrl'
     */
    @Test
    public void errorUrlTest() {
        // TODO: test errorUrl
    }

    /**
     * Test the property 'isEscrow'
     */
    @Test
    public void isEscrowTest() {
        // TODO: test isEscrow
    }

    /**
     * Test the property 'isMerchant'
     */
    @Test
    public void isMerchantTest() {
        // TODO: test isMerchant
    }

}
