/*
 * NabooApi V1
 * Here you have the first version of the naboo api to create checkout automatically
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.JsonElement;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets TransactionStatusEnum
 */
@JsonAdapter(TransactionStatusEnum.Adapter.class)
public enum TransactionStatusEnum {
  
  PENDING("pending"),
  
  PAID("paid"),
  
  DONE("done"),
  
  PART_PAID("part_paid");

  private String value;

  TransactionStatusEnum(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static TransactionStatusEnum fromValue(String value) {
    for (TransactionStatusEnum b : TransactionStatusEnum.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<TransactionStatusEnum> {
    @Override
    public void write(final JsonWriter jsonWriter, final TransactionStatusEnum enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public TransactionStatusEnum read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return TransactionStatusEnum.fromValue(value);
    }
  }

  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
    String value = jsonElement.getAsString();
    TransactionStatusEnum.fromValue(value);
  }
}

