/*
 * NabooApi V1
 * Here you have the first version of the naboo api to create checkout automatically
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.CashOutOrangeRequest;
import org.openapitools.client.model.CashOutResponse;
import org.openapitools.client.model.CashOutWaveRequest;
import org.openapitools.client.model.HTTPValidationError;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for CashoutApi
 */
@Disabled
public class CashoutApiTest {

    private final CashoutApi api = new CashoutApi();

    /**
     * Cash Out Orange Money
     *
     * This endpoint enables a user to withdraw funds from their NabooPay account to their Orange Money account. Authentication is required, and users with the &#39;dev&#39; role are not permitted to perform this operation. The amount to be withdrawn must be positive and within the user&#39;s available balance. The user&#39;s account must be active and registered in the system. After validation, the user&#39;s account balance is adjusted accordingly, and the transaction is logged for record-keeping.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void cashOutOrangeMoneyCashoutOrangeMoneyPostTest() throws ApiException {
        CashOutOrangeRequest cashOutOrangeRequest = null;
        CashOutResponse response = api.cashOutOrangeMoneyCashoutOrangeMoneyPost(cashOutOrangeRequest);
        // TODO: test validations
    }

    /**
     * Cash Out Wave
     *
     * This endpoint allows a user to withdraw funds from their NabooPay account to their Wave account. The user must be authenticated and not possess the &#39;dev&#39; role. The withdrawal amount must be greater than 10 and not exceed the user&#39;s account balance. The user&#39;s account must exist and be active. Upon successful validation, the system updates the user&#39;s account balance and records the transaction for tracking purposes.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void cashOutWaveCashoutWavePostTest() throws ApiException {
        CashOutWaveRequest cashOutWaveRequest = null;
        CashOutResponse response = api.cashOutWaveCashoutWavePost(cashOutWaveRequest);
        // TODO: test validations
    }

}
